import { WHATSAPP_NUMBER } from "./constants";

export type ResearchSaaS = {
  id: string;
  slug: string;
  categoryKey: string;
  categoryLabel: string;
  selectionRank: number;
  name: string;
  author?: string;
  sourcePlatform: "CodeCanyon / Envato Market";
  productUrl: string;
  regularPriceObservedUsd?: number | null;
  extendedPriceObservedUsd?: number | null;
  salesObserved?: number | null;
  ratingObserved?: number | null;
  observedAt: "2026-09-16";
  shortDescription: string;
  targetCustomers: string[];
  techStack?: string[];
  multiTenant: true | false | "needs-audit";
  saasEligible: boolean;
  demoUrls: Array<{ label: string; url: string | null; note?: string }>;
  demoCredentials: Array<{
    role: string;
    username: string;
    password: string;
    loginUrl?: string | null;
    note?: string;
  }>;
  dependencies: string[];
  externalCosts: string[];
  riskFlags?: string[];
  demoNote?: string;
  mercoScreenshots?: string[];
  sourceVerified: true;
  licenseVerified: false;
  commerciallyAvailable: false;
  status: "research";
};

/**
 * Catalogue de RECHERCHE MERCO — 40 candidats observés sur CodeCanyon / Envato Market le 16 septembre 2026.
 *
 * Règle : aucun produit de ce fichier n'est inclus dans l'abonnement MERCO.
 * `licenseVerified`, `commerciallyAvailable` et `status` passent à "actif" UNIQUEMENT
 * après achat/audit manuel MERCO. Ne jamais inventer une licence conforme.
 */
export const RESEARCH_CATEGORIES = [
  { key: "crm", label: "CRM & ventes" },
  { key: "reservation", label: "Réservation" },
  { key: "ecommerce", label: "E-commerce" },
  { key: "education", label: "Éducation" },
  { key: "rh", label: "RH & gestion" },
  { key: "sites", label: "Création de sites" },
  { key: "logistique", label: "Logistique" },
  { key: "whatsapp", label: "WhatsApp & relation client" },
] as const;

export const researchCatalog: ResearchSaaS[] = [
  /* ─────────────────────────── CRM & ventes ─────────────────────────── */
  {
    id: "grow-crm-saas",
    slug: "grow-crm-saas",
    categoryKey: "crm",
    categoryLabel: "CRM & ventes",
    selectionRank: 1,
    name: "Grow CRM SaaS",
    author: "NextLoop",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/grow-crm-saas-laravel-project-management-multitenancy/45363769",
    regularPriceObservedUsd: 89,
    salesObserved: 574,
    ratingObserved: 4.85,
    observedAt: "2026-09-16",
    shortDescription: "CRM SaaS Laravel très mature : vrai multi-tenant, sous-domaines clients et bases de données séparées. Candidat prioritaire MERCO.",
    targetCustomers: ["agences SaaS", "revendeurs CRM", "entrepreneurs multi-sous-domaines"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [
      { label: "Démo Owner (SaaS)", url: "https://saas.growcrm.io/app-admin" },
      { label: "Démo Client (sous-domaine)", url: "https://customer.growcrm.io" },
    ],
    demoCredentials: [
      { role: "Owner", username: "owner@example.com", password: "growcrm", loginUrl: "https://saas.growcrm.io/app-admin" },
      { role: "Client", username: "customer@example.com", password: "growcrm", loginUrl: "https://customer.growcrm.io" },
    ],
    dependencies: [],
    externalCosts: [],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "sales-saas-business-sales-crm",
    slug: "sales-saas-business-sales-crm",
    categoryKey: "crm",
    categoryLabel: "CRM & ventes",
    selectionRank: 2,
    name: "Sales SaaS — Business Sales CRM",
    author: "WorkDo",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/sales-saas-business-sales-crm/30241292",
    regularPriceObservedUsd: 29,
    salesObserved: 336,
    ratingObserved: 5.0,
    observedAt: "2026-09-16",
    shortDescription: "SaaS CRM de vente multi-tenant de WorkDo : gestion des ventes, pipelines et activités par entreprise abonnée.",
    targetCustomers: ["entreprises B2B", "équipes commerciales", "revendeurs SaaS"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [{ label: "Démo (login)", url: "https://demo.workdo.io/sales-saas/login" }],
    demoCredentials: [
      { role: "Super Admin", username: "superadmin@example.com", password: "password", loginUrl: "https://demo.workdo.io/sales-saas/login" },
      { role: "Company", username: "company@example.com", password: "password", loginUrl: "https://demo.workdo.io/sales-saas/login" },
      { role: "Sales User", username: "sarahjohnson@example.com", password: "password", loginUrl: "https://demo.workdo.io/sales-saas/login" },
    ],
    dependencies: [],
    externalCosts: [],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "leadhub-multitenant-saas-crm",
    slug: "leadhub-multitenant-saas-crm",
    categoryKey: "crm",
    categoryLabel: "CRM & ventes",
    selectionRank: 3,
    name: "LeadHub — Multi-Tenant SaaS CRM",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/leadhub-multitenant-saas-crm-with-lead-pipelines-forms-automations/63311759",
    regularPriceObservedUsd: 39,
    salesObserved: 56,
    ratingObserved: 4.43,
    observedAt: "2026-09-16",
    shortDescription: "CRM SaaS multi-tenant Laravel/Filament avec pipelines de leads, formulaires et automations.",
    targetCustomers: ["équipes commerciales", "revendeurs CRM", "entrepreneurs SaaS"],
    techStack: ["Laravel", "Filament"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [],
    demoNote: "La démo officielle est accessible depuis la page CodeCanyon du vendeur.",
    demoCredentials: [],
    dependencies: [],
    externalCosts: [],
    riskFlags: ["URL directe de démo non confirmée – utiliser le bouton Live Preview de la page CodeCanyon", "Aucun identifiant statique de démo confirmé"],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "perfex-crm-saas-module",
    slug: "perfex-crm-saas-module",
    categoryKey: "crm",
    categoryLabel: "CRM & ventes",
    selectionRank: 4,
    name: "Perfex CRM SaaS Module",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/perfex-crm-saas-module-transform-your-perfex-crm-into-a-powerful-multitenancy-solution/46070331",
    regularPriceObservedUsd: 99,
    salesObserved: 1100,
    ratingObserved: 4.98,
    observedAt: "2026-09-16",
    shortDescription: "Module qui transforme Perfex CRM en solution multitenancy. Nécessite une licence Perfex CRM 3.1+ à part.",
    targetCustomers: ["revendeurs SaaS CRM", "déjà utilisateurs de Perfex", "agences"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [
      { label: "Démo Admin", url: "https://perfextosaas.com/admin" },
      { label: "Démo Client", url: "https://perfextosaas.com" },
    ],
    demoCredentials: [
      { role: "Admin", username: "admin@admin.com", password: "password", loginUrl: "https://perfextosaas.com/admin" },
      { role: "Client", username: "customer@customer.com", password: "password", loginUrl: "https://perfextosaas.com" },
    ],
    dependencies: ["Perfex CRM 3.1+ — à acheter/licencier séparément"],
    externalCosts: [],
    riskFlags: ["Identifiants de démo à revérifier avant publication – la démo peut être réinitialisée"],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "coravo-ai-powered-crm-erp-saas",
    slug: "coravo-ai-powered-crm-erp-saas",
    categoryKey: "crm",
    categoryLabel: "CRM & ventes",
    selectionRank: 5,
    name: "Coravo — AI-Powered CRM & ERP SaaS",
    author: "SoftEntra",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/coravo-aipowered-crm-erp-saas-platform/64710287",
    regularPriceObservedUsd: 79,
    observedAt: "2026-09-16",
    shortDescription: "Plateforme CRM & ERP SaaS Laravel 13 + Vue 3, multi-tenant / white-label annoncée.",
    targetCustomers: ["entreprises multi-services", "revendeurs SaaS"],
    techStack: ["Laravel 13", "Vue 3"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [{ label: "Démo (connexion one-click)", url: "https://coravo-saas.softentra.com" }],
    demoCredentials: [],
    dependencies: [],
    externalCosts: [],
    riskFlags: ["Produit très récent, faible historique de ventes – audit renforcé avant activation", "Démo one-click sans identifiants statiques"],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },

  /* ─────────────────────────── Réservation ─────────────────────────── */
  {
    id: "bookinggo-saas",
    slug: "bookinggo-saas",
    categoryKey: "reservation",
    categoryLabel: "Réservation",
    selectionRank: 1,
    name: "BookingGo SaaS",
    author: "WorkDo",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/bookinggo-saas-multi-business-appointment-booking-and-scheduling/50585829",
    regularPriceObservedUsd: 69,
    salesObserved: 268,
    ratingObserved: 4.94,
    observedAt: "2026-09-16",
    shortDescription: "SaaS de rendez-vous et réservation multi-business de WorkDo : chaque entreprise gère sa propre activité.",
    targetCustomers: ["salons", "coachs", "consultants", "revendeurs SaaS réservation"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [{ label: "Démo (login)", url: "https://bookinggo-demo.workdo.io/login" }],
    demoCredentials: [
      { role: "Super Admin", username: "superadmin@example.com", password: "1234", loginUrl: "https://bookinggo-demo.workdo.io/login" },
      { role: "Company", username: "company@example.com", password: "1234", loginUrl: "https://bookinggo-demo.workdo.io/login" },
    ],
    dependencies: [],
    externalCosts: [],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "aoxio-saas-multibusiness-booking",
    slug: "aoxio-saas-multibusiness-booking",
    categoryKey: "reservation",
    categoryLabel: "Réservation",
    selectionRank: 2,
    name: "Aoxio — SaaS Multi-Business Booking",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/aoxio-saas-multibusiness-service-booking-software/33026229",
    regularPriceObservedUsd: 39,
    salesObserved: 715,
    ratingObserved: 4.81,
    observedAt: "2026-09-16",
    shortDescription: "Logiciel de réservation multi-business avec prise en charge du domaine personnalisé par tenant.",
    targetCustomers: ["salons", "garages", "services à domicile", "revendeurs SaaS"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [
      { label: "Démo principale", url: "https://aoxiosaas.site" },
      { label: "Exemple domaine personnalisé", url: "https://aoxio.online" },
    ],
    demoCredentials: [],
    dependencies: [],
    externalCosts: [],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "bookapp-multivendor-booking",
    slug: "bookapp-multivendor-booking",
    categoryKey: "reservation",
    categoryLabel: "Réservation",
    selectionRank: 3,
    name: "Bookapp — Service & Appointment Booking (SAAS)",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/bookapp-multivendor-service-appointment-booking-laravel-website-subscription-based/54240416",
    regularPriceObservedUsd: 49,
    salesObserved: 171,
    observedAt: "2026-09-16",
    shortDescription: "Marketplace Laravel de réservation multi-vendeurs avec abonnements : front, admin, vendeurs et staff.",
    targetCustomers: ["marketplaces de services", "plateformes multi-vendeurs"],
    techStack: ["Laravel"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [
      { label: "Front", url: "https://php82.kreativdev.com/bookapp/" },
      { label: "Admin", url: "https://php82.kreativdev.com/bookapp/demo/admin/" },
      { label: "Vendor", url: "https://php82.kreativdev.com/bookapp/demo/vendor/login/" },
      { label: "Staff", url: "https://php82.kreativdev.com/bookapp/demo/staff/login/" },
    ],
    demoCredentials: [
      { role: "Admin", username: "admin", password: "admin", loginUrl: "https://php82.kreativdev.com/bookapp/demo/admin/" },
      { role: "Vendor", username: "tomhughes", password: "123456", loginUrl: "https://php82.kreativdev.com/bookapp/demo/vendor/login/" },
      { role: "Staff", username: "liamjohnson", password: "12345678", loginUrl: "https://php82.kreativdev.com/bookapp/demo/staff/login/" },
    ],
    dependencies: [],
    externalCosts: [],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "bookin-saas-multi-vendor-booking",
    slug: "bookin-saas-multi-vendor-booking",
    categoryKey: "reservation",
    categoryLabel: "Réservation",
    selectionRank: 4,
    name: "Bookin SaaS — Multi Vendor Service Booking",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/bookin-saas-multi-vendor-service-booking-system/55623951",
    regularPriceObservedUsd: 59,
    salesObserved: 89,
    ratingObserved: 4.0,
    observedAt: "2026-09-16",
    shortDescription: "Système de réservation multi-vendeurs SaaS à vérifier : la démo doit être re-confirmée avant publication.",
    targetCustomers: ["plateformes multi-vendeurs", "services locaux"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [{ label: "Démo (à revérifier)", url: "https://nativecode.in/demo/bookin", note: "URL observée – à revérifier avant publication" }],
    demoCredentials: [],
    dependencies: [],
    externalCosts: [],
    riskFlags: ["Démo à revérifier avant publication", "Aucun identifiant statique de démo confirmé"],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "bookingdo-saas",
    slug: "bookingdo-saas",
    categoryKey: "reservation",
    categoryLabel: "Réservation",
    selectionRank: 5,
    name: "BookingDo SaaS",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/bookingdo-saas-multi-business-appointment-service-booking-saas/42347177",
    regularPriceObservedUsd: 29,
    salesObserved: 286,
    observedAt: "2026-09-16",
    shortDescription: "SaaS de réservation multi-business : rendez-vous et services par porteur de compte.",
    targetCustomers: ["salons", "centres de service", "revendeurs SaaS"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [{ label: "Démo", url: "https://bookingdo.paponapps.co.in" }],
    demoCredentials: [
      { role: "Super Admin", username: "admin@gmail.com", password: "123456", loginUrl: "https://bookingdo.paponapps.co.in" },
      { role: "Service Provider", username: "vendor1@gmail.com", password: "123456", loginUrl: "https://bookingdo.paponapps.co.in" },
    ],
    dependencies: [],
    externalCosts: [],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },

  /* ─────────────────────────── E-commerce ─────────────────────────── */
  {
    id: "ecommet-multitenant-ecommerce-builder",
    slug: "ecommet-multitenant-ecommerce-builder",
    categoryKey: "ecommerce",
    categoryLabel: "E-commerce",
    selectionRank: 1,
    name: "Ecommet — White-Label Multitenant Ecommerce Builder",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/ecommet-multitenant-ecommerce-website-saas/57240303",
    regularPriceObservedUsd: 49,
    salesObserved: 229,
    ratingObserved: 5.0,
    observedAt: "2026-09-16",
    shortDescription: "Constructeur de boutiques e-commerce multi-tenant white-label : chaque tenant crée sa boutique.",
    targetCustomers: ["revendeurs SaaS e-commerce", "agences web", "entrepreneurs en ligne"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [
      { label: "Main", url: "https://ecommet.xyz/" },
      { label: "Admin", url: "https://ecommet.xyz/admin/" },
      { label: "Login tenant", url: "https://ecommet.xyz/login/" },
      { label: "Login client", url: "https://ecommet.xyz/skinflow/customer/login/" },
      { label: "Exemple boutique", url: "https://manti.ecommet.xyz/" },
    ],
    demoCredentials: [],
    dependencies: [],
    externalCosts: [],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "storego-saas-online-store-builder",
    slug: "storego-saas-online-store-builder",
    categoryKey: "ecommerce",
    categoryLabel: "E-commerce",
    selectionRank: 2,
    name: "StoreGo SaaS — Online Store Builder",
    author: "WorkDo",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/storego-saas-online-store-builder/31116337",
    regularPriceObservedUsd: 24,
    salesObserved: 1470,
    ratingObserved: 5.0,
    observedAt: "2026-09-16",
    shortDescription: "Générateur de boutiques en ligne SaaS multi-tenant de WorkDo, très adopté.",
    targetCustomers: ["revendeurs SaaS e-commerce", "créateurs de boutiques"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [{ label: "Démo (login)", url: "https://demo.workdo.io/storego-saas/login" }],
    demoCredentials: [
      { role: "Super Admin", username: "superadmin@example.com", password: "password", loginUrl: "https://demo.workdo.io/storego-saas/login" },
      { role: "Company", username: "company@example.com", password: "password", loginUrl: "https://demo.workdo.io/storego-saas/login" },
    ],
    dependencies: [],
    externalCosts: [],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "botble-ecommerce-saas",
    slug: "botble-ecommerce-saas",
    categoryKey: "ecommerce",
    categoryLabel: "E-commerce",
    selectionRank: 3,
    name: "Botble Ecommerce SaaS — Multi-tenant Store Platform",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/botble-ecommerce-saas-multitenant-store-platform/65116868",
    regularPriceObservedUsd: 69,
    observedAt: "2026-09-16",
    shortDescription: "Plateforme multi-tenant de stores de Botble (éditeur reconnu) : opérateur + stores clients.",
    targetCustomers: ["revendeurs SaaS e-commerce", "opérateurs de marketplace"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [
      { label: "Landing", url: "https://saas.botble.com" },
      { label: "Store 1", url: "https://demo1.saas.botble.com" },
      { label: "Store 1 admin", url: "https://demo1.saas.botble.com/saas-admin" },
      { label: "Store 2", url: "https://demo2.saas.botble.com" },
      { label: "Store 2 admin", url: "https://demo2.saas.botble.com/saas-admin" },
    ],
    demoCredentials: [
      { role: "Operator", username: "operator@botble.com", password: "12345678", loginUrl: "https://saas.botble.com/saas-admin/operator" },
      { role: "Store 1 admin", username: "demo1@botble.com", password: "12345678", loginUrl: "https://demo1.saas.botble.com/saas-admin" },
      { role: "Store 2 admin", username: "demo2@botble.com", password: "12345678", loginUrl: "https://demo2.saas.botble.com/saas-admin" },
    ],
    dependencies: [],
    externalCosts: [],
    riskFlags: ["Produit très récent – audit d'architecture avant activation"],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "nazmart-multitenancy-ecommerce",
    slug: "nazmart-multitenancy-ecommerce",
    categoryKey: "ecommerce",
    categoryLabel: "E-commerce",
    selectionRank: 4,
    name: "Nazmart — Multi-Tenancy eCommerce Platform (SAAS)",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/nazmart-multitenancy-ecommerce-platform-saas/42802410",
    regularPriceObservedUsd: 69,
    salesObserved: 533,
    ratingObserved: 4.51,
    observedAt: "2026-09-16",
    shortDescription: "Plateforme e-commerce multi-tenant avec domaines personnalisés par tenant.",
    targetCustomers: ["revendeurs SaaS e-commerce", "porteurs de marketplace"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [
      { label: "Main", url: "https://nazmart.net/" },
      { label: "Custom domain admin", url: "https://hexfashion.xyz/admin" },
    ],
    demoCredentials: [
      { role: "Super Admin", username: "super_admin", password: "12345678", loginUrl: "https://nazmart.net/" },
      { role: "Front user", username: "test", password: "12345678", loginUrl: "https://nazmart.net/" },
      { role: "Custom domain admin", username: "super_admin", password: "12345678", loginUrl: "https://hexfashion.xyz/admin" },
    ],
    dependencies: [],
    externalCosts: [],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "storemart-saas-grocery-delivery",
    slug: "storemart-saas-grocery-delivery",
    categoryKey: "ecommerce",
    categoryLabel: "E-commerce",
    selectionRank: 5,
    name: "StoreMart SaaS — Grocery Delivery System",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/storemart-saas-grocery-delivery-system/38430497",
    regularPriceObservedUsd: 14,
    salesObserved: 329,
    observedAt: "2026-09-16",
    shortDescription: "SaaS de livraison de courses multi-boutiques : commandes, shop owners et livraison.",
    targetCustomers: ["livraison de courses", "épiceries", "revendeurs SaaS"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [{ label: "Démo", url: "https://store-mart.paponapps.co.in" }],
    demoCredentials: [
      { role: "Admin", username: "admin@gmail.com", password: "123456", loginUrl: "https://store-mart.paponapps.co.in" },
      { role: "Shop Owner", username: "user@yopmail.com", password: "123456", loginUrl: "https://store-mart.paponapps.co.in" },
    ],
    dependencies: [],
    externalCosts: [],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },

  /* ─────────────────────────── Éducation ─────────────────────────── */
  {
    id: "eschool-saas",
    slug: "eschool-saas",
    categoryKey: "education",
    categoryLabel: "Éducation",
    selectionRank: 1,
    name: "eSchool SaaS",
    author: "WRTeam",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/eschool-saas-school-management-system-with-student-parents-teacher-flutter-app-laravel-admin/49307764",
    regularPriceObservedUsd: 79,
    salesObserved: 993,
    ratingObserved: 4.94,
    observedAt: "2026-09-16",
    shortDescription: "Système de gestion scolaire multi-écoles avec base et branding par école, plus app Flutter.",
    targetCustomers: ["établissements scolaires", "écoles privées", "revendeurs SaaS éducation"],
    techStack: ["Laravel", "Flutter (app mobile)"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [
      { label: "Landing", url: "https://eschool-saas.wrteam.me" },
      { label: "Démo école", url: "https://crestwood-academy.eschool-saas.wrteam.me" },
    ],
    demoCredentials: [],
    dependencies: [],
    externalCosts: [],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "ekattor-8-school-management",
    slug: "ekattor-8-school-management",
    categoryKey: "education",
    categoryLabel: "Éducation",
    selectionRank: 2,
    name: "Ekattor 8 — Laravel School Management System (SAAS)",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/ekattor-8-school-management-system/39611172",
    regularPriceObservedUsd: 55,
    extendedPriceObservedUsd: 350,
    salesObserved: 546,
    observedAt: "2026-09-16",
    shortDescription: "Gestion scolaire en mode SaaS (SAAS) de Creativeitem avec comptes admin, enseignant et élève.",
    targetCustomers: ["écoles", "centres de formation", "revendeurs SaaS éducation"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [{ label: "Démo (login)", url: "https://demo.creativeitem.com/ekattor8/login" }],
    demoCredentials: [
      { role: "Admin", username: "admin@example.com", password: "1234", loginUrl: "https://demo.creativeitem.com/ekattor8/login" },
      { role: "Teacher", username: "teacher@example.com", password: "1234", loginUrl: "https://demo.creativeitem.com/ekattor8/login" },
      { role: "Student", username: "student@example.com", password: "1234", loginUrl: "https://demo.creativeitem.com/ekattor8/login" },
    ],
    dependencies: [],
    externalCosts: [],
    riskFlags: ["Identifiants souvent publiés dans l'écosystème Creativeitem – à revérifier avant affichage"],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "ramom-school-subscription-saas",
    slug: "ramom-school-subscription-saas",
    categoryKey: "education",
    categoryLabel: "Éducation",
    selectionRank: 3,
    name: "Ramom School Subscription (SaaS)",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/ramom-school-subscription-saas/45121444",
    regularPriceObservedUsd: 50,
    salesObserved: 354,
    observedAt: "2026-09-16",
    shortDescription: "SaaS de gestion scolaire multi-écoles construit sur Ramom School Multi Branch.",
    targetCustomers: ["écoles", "campus multi-écoles", "revendeurs SaaS éducation"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [
      { label: "SaaS", url: "https://saas.ramomcoder.com" },
      { label: "Démo école 1", url: "https://iconschool.ramomcoder.com" },
      { label: "Démo école 2", url: "https://oxford.ramomcoder.com" },
    ],
    demoCredentials: [],
    dependencies: ["Ramom School Multi Branch — à acquérir séparément"],
    externalCosts: [],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "quizora-ai-quiz-exam-saas",
    slug: "quizora-ai-quiz-exam-saas",
    categoryKey: "education",
    categoryLabel: "Éducation",
    selectionRank: 4,
    name: "Quizora — AI Quiz & Exam SaaS Platform",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/quizora-ai-quiz-exam-saas-platform-with-payments-and-certificates/63989606",
    regularPriceObservedUsd: 59,
    observedAt: "2026-09-16",
    shortDescription: "Plateforme SaaS de quiz et examens avec IA, paiements et certificats.",
    targetCustomers: ["écoles", "centres de formation", "revendeurs SaaS éducation"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [
      { label: "Base", url: "https://quizora.ishalabs.com/" },
      { label: "Admin", url: "https://quizora.ishalabs.com/admin" },
      { label: "Creator", url: "https://quizora.ishalabs.com/creator" },
      { label: "Login client", url: "https://quizora.ishalabs.com/login" },
    ],
    demoCredentials: [
      { role: "Admin", username: "admin@quizora.app", password: "password", loginUrl: "https://quizora.ishalabs.com/admin" },
      { role: "Creator", username: "priya@demo.quiz", password: "password", loginUrl: "https://quizora.ishalabs.com/creator" },
      { role: "Customer", username: "alice@demo.quiz", password: "password", loginUrl: "https://quizora.ishalabs.com/login" },
    ],
    dependencies: [],
    externalCosts: ["API IA (selon usage) — non incluse automatiquement dans MERCO"],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "smartschool-saas-aspnet-core",
    slug: "smartschool-saas-aspnet-core",
    categoryKey: "education",
    categoryLabel: "Éducation",
    selectionRank: 5,
    name: "SmartSchool SaaS — ASP.NET Core",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/smartschool-saas-aspnet-core-school-management-system/64279997",
    regularPriceObservedUsd: 59,
    salesObserved: 1,
    observedAt: "2026-09-16",
    shortDescription: "Système de gestion scolaire SaaS en ASP.NET Core, très récent sur la place de marché.",
    targetCustomers: ["écoles", "établissements", "revendeurs SaaS éducation"],
    techStack: ["ASP.NET Core"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [{ label: "Démo (login)", url: "http://smartschoolsaas.linacode.pro/login" }],
    demoCredentials: [],
    dependencies: [],
    externalCosts: [],
    riskFlags: ["Produit très récent (env. 1 vente observée)", "Audit renforcé avant activation"],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },

  /* ─────────────────────────── RH & gestion ─────────────────────────── */
  {
    id: "erpgo-saas",
    slug: "erpgo-saas",
    categoryKey: "rh",
    categoryLabel: "RH & gestion",
    selectionRank: 1,
    name: "ERPGo SaaS",
    author: "WorkDo",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/erpgo-saas-all-in-one-business-erp-with-project-account-hrm-crm-pos/33263426",
    regularPriceObservedUsd: 69,
    salesObserved: 2390,
    ratingObserved: 4.9,
    observedAt: "2026-09-16",
    shortDescription: "ERP SaaS tout-en-un : projets, comptabilité, RH, CRM et POS pour chaque entreprise abonnée.",
    targetCustomers: ["PME", "agences", "revendeurs SaaS ERP"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [{ label: "Démo (login)", url: "https://demo.workdo.io/erpgo-saas/login" }],
    demoCredentials: [
      { role: "Super Admin", username: "superadmin@example.com", password: "1234", loginUrl: "https://demo.workdo.io/erpgo-saas/login" },
      { role: "Company", username: "company@example.com", password: "1234", loginUrl: "https://demo.workdo.io/erpgo-saas/login" },
      { role: "Employee", username: "john.smith@company.com", password: "1234", loginUrl: "https://demo.workdo.io/erpgo-saas/login" },
      { role: "Customer", username: "sarah.johnson@client.com", password: "1234", loginUrl: "https://demo.workdo.io/erpgo-saas/login" },
      { role: "Vendor", username: "alex.vendor@supplier.com", password: "1234", loginUrl: "https://demo.workdo.io/erpgo-saas/login" },
    ],
    dependencies: [],
    externalCosts: [],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "hrm-saas-hr-payroll-tool",
    slug: "hrm-saas-hr-payroll-tool",
    categoryKey: "rh",
    categoryLabel: "RH & gestion",
    selectionRank: 2,
    name: "HRM SaaS — HR and Payroll Tool",
    author: "WorkDo",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/hrm-saas-hr-and-payroll-tool/25982934",
    regularPriceObservedUsd: 39,
    salesObserved: 1280,
    ratingObserved: 4.88,
    observedAt: "2026-09-16",
    shortDescription: "Outil RH et paie multi-tenant de WorkDo : congés, présences, salaires par entreprise.",
    targetCustomers: ["PME", "services RH", "revendeurs SaaS RH"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [{ label: "Démo (login)", url: "https://demo.workdo.io/hrm-saas/login" }],
    demoCredentials: [
      { role: "Super Admin", username: "superadmin@example.com", password: "password", loginUrl: "https://demo.workdo.io/hrm-saas/login" },
      { role: "Company", username: "company@example.com", password: "password", loginUrl: "https://demo.workdo.io/hrm-saas/login" },
      { role: "HR", username: "maggie93@example.com", password: "password", loginUrl: "https://demo.workdo.io/hrm-saas/login" },
      { role: "Employee", username: "qwaters@example.com", password: "password", loginUrl: "https://demo.workdo.io/hrm-saas/login" },
    ],
    dependencies: [],
    externalCosts: [],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "hrm-saas-human-resource-management",
    slug: "hrm-saas-human-resource-management",
    categoryKey: "rh",
    categoryLabel: "RH & gestion",
    selectionRank: 3,
    name: "HRM SAAS — Human Resource Management",
    author: "ajay138",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/hrm-saas-human-resource-management/23400912",
    regularPriceObservedUsd: 49,
    extendedPriceObservedUsd: 124,
    observedAt: "2026-09-16",
    shortDescription: "Gestion RH en mode SaaS : admin, employés et super admin dans une même plateforme.",
    targetCustomers: ["PME", "services RH", "revendeurs SaaS RH"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [{ label: "Démo", url: "https://hrm-saas.froid.works" }],
    demoCredentials: [
      { role: "Admin", username: "admin@example.com", password: "123456", loginUrl: "https://hrm-saas.froid.works" },
      { role: "Employee", username: "employee@example.com", password: "123456", loginUrl: "https://hrm-saas.froid.works" },
      { role: "Super Admin", username: "superadmin@example.com", password: "123456", loginUrl: "https://hrm-saas.froid.works" },
    ],
    dependencies: [],
    externalCosts: [],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "stocky-saas-pos-inventory",
    slug: "stocky-saas-pos-inventory",
    categoryKey: "rh",
    categoryLabel: "RH & gestion",
    selectionRank: 4,
    name: "Stocky SaaS — POS / Inventory / ERP / HRM",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/stocky-pos-inventory-management-saas/62663753",
    regularPriceObservedUsd: 59,
    salesObserved: 130,
    ratingObserved: 5.0,
    observedAt: "2026-09-16",
    shortDescription: "SaaS POS / inventaire / ERP / RH multi-tenant avec chaque tenant sur son sous-domaine.",
    targetCustomers: ["commerces", "points de vente", "revendeurs SaaS gestion"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [
      { label: "Landing", url: "https://stockysaas.xyz/" },
      { label: "Central admin", url: "https://stockysaas.xyz/super/login" },
      { label: "Tenant", url: "https://john.stockysaas.xyz" },
    ],
    demoCredentials: [
      { role: "Central admin", username: "superadmin@stockysaas.site", password: "123456", loginUrl: "https://stockysaas.xyz/super/login" },
      { role: "Tenant", username: "john@stockysaas.site", password: "12345678", loginUrl: "https://john.stockysaas.xyz" },
    ],
    dependencies: [],
    externalCosts: [],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "hrmifly-saas",
    slug: "hrmifly-saas",
    categoryKey: "rh",
    categoryLabel: "RH & gestion",
    selectionRank: 5,
    name: "Hrmifly SAAS",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/hrmifly-saas-complete-payroll-and-hr-management-system-hrm/58648534",
    regularPriceObservedUsd: 49,
    salesObserved: 68,
    ratingObserved: 5.0,
    observedAt: "2026-09-16",
    shortDescription: "SaaS complet de paie et gestion RH avec comptes admin.",
    targetCustomers: ["PME", "dirigeants", "revendeurs SaaS RH"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [{ label: "Démo", url: "https://hrmifly.codeifly.in" }],
    demoCredentials: [
      { role: "Admin", username: "admin@example.com", password: "12345678", loginUrl: "https://hrmifly.codeifly.in" },
    ],
    dependencies: [],
    externalCosts: [],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },

  /* ─────────────────────────── Création de sites ─────────────────────────── */
  {
    id: "businesso-ai-website-builder-saas",
    slug: "businesso-ai-website-builder-saas",
    categoryKey: "sites",
    categoryLabel: "Création de sites",
    selectionRank: 1,
    name: "Businesso — AI Powered Website Builder SaaS",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/businesso-business-website-builder-saas-multitenancy/34880110",
    regularPriceObservedUsd: 49,
    extendedPriceObservedUsd: 199,
    salesObserved: 1100,
    ratingObserved: 4.78,
    observedAt: "2026-09-16",
    shortDescription: "Constructeur de sites web SaaS multitenancy boosté à l'IA : chaque tenant crée son site.",
    targetCustomers: ["agences web", "revendeurs SaaS création de sites"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [
      { label: "Main", url: "https://biznesso.vip/" },
      { label: "Admin", url: "https://biznesso.vip/admin/" },
      { label: "Login tenant", url: "https://biznesso.vip/login/" },
      { label: "Login client", url: "https://boutique.biznesso.vip/user/login/" },
    ],
    demoCredentials: [],
    dependencies: [],
    externalCosts: ["API IA (selon usage) — non incluse automatiquement dans MERCO"],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "multisaas-multipurpose-website-builder",
    slug: "multisaas-multipurpose-website-builder",
    categoryKey: "sites",
    categoryLabel: "Création de sites",
    selectionRank: 2,
    name: "MultiSaas — Multi-Tenancy Multipurpose Website Builder",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/multisass-multitenancy-multipurpose-website-builder-sass/41892997",
    regularPriceObservedUsd: 59,
    salesObserved: 654,
    ratingObserved: 4.46,
    observedAt: "2026-09-16",
    shortDescription: "Constructeur de sites multi-tenant polyvalent : sous-domaines, domaines personnalisés et rôles.",
    targetCustomers: ["agences web", "revendeurs SaaS", "créateurs de sites"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [
      { label: "Super Admin", url: "https://multipurposesass.com/admin" },
      { label: "Custom domain", url: "https://picajobfinder.xyz/admin" },
      { label: "Subdomain", url: "https://donation.multipurposesass.com/admin" },
    ],
    demoCredentials: [
      { role: "Super Admin", username: "super_admin", password: "12345678", loginUrl: "https://multipurposesass.com/admin" },
      { role: "Front user", username: "test", password: "12345678", loginUrl: "https://multipurposesass.com/admin" },
      { role: "Custom domain admin", username: "super_admin", password: "12345678", loginUrl: "https://picajobfinder.xyz/admin" },
      { role: "Subdomain admin", username: "super_admin", password: "12345678", loginUrl: "https://donation.multipurposesass.com/admin" },
    ],
    dependencies: [],
    externalCosts: [],
    riskFlags: ["Mise à jour moins récente – audit sécurité/compatibilité nécessaire"],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "webby-ai-nocode-website-builder",
    slug: "webby-ai-nocode-website-builder",
    categoryKey: "sites",
    categoryLabel: "Création de sites",
    selectionRank: 3,
    name: "Webby — AI No-Code Website Builder SaaS",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/webby-aipowered-nocode-website-builder-saas-platform/61857601",
    regularPriceObservedUsd: 29,
    extendedPriceObservedUsd: 350,
    salesObserved: 213,
    ratingObserved: 4.11,
    observedAt: "2026-09-16",
    shortDescription: "Constructeur de sites no-code SaaS propulsé par IA (prix promo observé).",
    targetCustomers: ["agences web", "freelances", "revendeurs SaaS création de sites"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [{ label: "Démo (à revérifier)", url: "https://webby.titansys.dev/", note: "URL observée – à revérifier avant publication" }],
    demoCredentials: [],
    dependencies: [],
    externalCosts: ["API IA (selon usage) — non incluse automatiquement dans MERCO"],
    riskFlags: ["URL de démo à revérifier avant publication", "Aucun identifiant statique de démo confirmé"],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "profilex-portfolio-builder",
    slug: "profilex-portfolio-builder",
    categoryKey: "sites",
    categoryLabel: "Création de sites",
    selectionRank: 4,
    name: "Profilex — Multitenant Portfolio Website Builder",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/profilex-portfolio-builder-saas-multiuser-profile/33283445",
    regularPriceObservedUsd: 49,
    salesObserved: 627,
    observedAt: "2026-09-16",
    shortDescription: "Constructeur de portfolios et profils multi-utilisateurs : chaque tenant a son site perso.",
    targetCustomers: ["professionnels", "freelances", "revendeurs SaaS"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [
      { label: "Main", url: "https://profilez.xyz/" },
      { label: "Admin", url: "https://profilez.xyz/admin/" },
      { label: "Login tenant", url: "https://profilez.xyz/login/" },
      { label: "Login client", url: "https://profilez.xyz/Rabiot/user/login/" },
      { label: "Exemple", url: "https://profilez.xyz/Rabiot/" },
    ],
    demoCredentials: [],
    dependencies: [],
    externalCosts: [],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "krikkit-ai-website-builder",
    slug: "krikkit-ai-website-builder",
    categoryKey: "sites",
    categoryLabel: "Création de sites",
    selectionRank: 5,
    name: "Krikkit — AI Website Builder SaaS Platform",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/krikkit-ai-website-builder-saas-platform-for-promptbased-site-generation/65055559",
    regularPriceObservedUsd: 49,
    extendedPriceObservedUsd: 297,
    salesObserved: 23,
    ratingObserved: 5.0,
    observedAt: "2026-09-16",
    shortDescription: "Constructeur de sites SaaS générés par prompts (IA), très récent, gardé en recherche.",
    targetCustomers: ["agences web", "créateurs de sites", "revendeurs SaaS"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [],
    demoNote: "La démo officielle est accessible depuis la page CodeCanyon du vendeur.",
    demoCredentials: [],
    dependencies: [],
    externalCosts: [],
    riskFlags: ["Produit très récent – garder en recherche", "URL exacte de la démo à revérifier (Live Preview CodeCanyon)"],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },

  /* ─────────────────────────── Logistique ─────────────────────────── */
  {
    id: "deprixa-plus-courier-logistics",
    slug: "deprixa-plus-courier-logistics",
    categoryKey: "logistique",
    categoryLabel: "Logistique",
    selectionRank: 1,
    name: "Deprixa Plus — Courier & Delivery Management | Logistics SaaS",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/deprixa-plus-the-ultimate-courier-logistics-saas-platform/63216725",
    regularPriceObservedUsd: 79,
    salesObserved: 45,
    observedAt: "2026-09-16",
    shortDescription: "Plateforme SaaS courrier & logistique multi-tenant annoncée : une installation pour plusieurs organisations.",
    targetCustomers: ["sociétés de livraison", "coursiers", "revendeurs SaaS logistique"],
    techStack: ["Laravel 12", "React 19"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [],
    demoNote: "La démo officielle est accessible depuis la page CodeCanyon du vendeur.",
    demoCredentials: [
      { role: "Super Admin", username: "admin@deprixa.com", password: "Admin@1234" },
      { role: "Admin demo", username: "admin@demo.deprixa.com", password: "Admin@1234" },
      { role: "Employee", username: "employee@demo.deprixa.com", password: "Admin@1234" },
      { role: "Driver", username: "driver@demo.deprixa.com", password: "Driver@1234" },
    ],
    dependencies: [],
    externalCosts: [],
    riskFlags: ["URL directe de démo non confirmée – Live Preview de la page CodeCanyon à revérifier"],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "we-courier-saas",
    slug: "we-courier-saas",
    categoryKey: "logistique",
    categoryLabel: "Logistique",
    selectionRank: 2,
    name: "We Courier SAAS — Multi-Tenancy Courier & Logistics",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/we-courier-saas-multitenancy-courier-and-logistics-management-merchant-delivery-app-with-admin/51166784",
    regularPriceObservedUsd: 99,
    salesObserved: 68,
    ratingObserved: 4.0,
    observedAt: "2026-09-16",
    shortDescription: "SaaS courrier & logistique multi-tenant avec admin, succursales, marchands et livraison.",
    targetCustomers: ["sociétés de livraison", "marchands", "revendeurs SaaS logistique"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [
      { label: "Admin", url: "https://wemaxdevs.xyz" },
      { label: "Company / Branch / Merchant", url: "https://company.wemaxdevs.xyz" },
    ],
    demoCredentials: [
      { role: "Admin", username: "admin@wemaxdevs.com", password: "12345678", loginUrl: "https://wemaxdevs.xyz" },
      { role: "Company", username: "company@wemaxdevs.com", password: "12345678", loginUrl: "https://company.wemaxdevs.xyz" },
      { role: "Branch", username: "branch@wemaxdevs.com", password: "12345678", loginUrl: "https://company.wemaxdevs.xyz/login" },
      { role: "Merchant", username: "merchant@wemaxdevs.com", password: "12345678", loginUrl: "https://company.wemaxdevs.xyz/login", note: "Merchant ID 2024" },
    ],
    dependencies: [],
    externalCosts: [],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "delivery-hub-saas",
    slug: "delivery-hub-saas",
    categoryKey: "logistique",
    categoryLabel: "Logistique",
    selectionRank: 3,
    name: "Delivery Hub SaaS — Parcel & Courier Management Tool",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/courier-management-system-saas/54499134",
    regularPriceObservedUsd: 39,
    salesObserved: 34,
    ratingObserved: 5.0,
    observedAt: "2026-09-16",
    shortDescription: "Outil SaaS de gestion colis et coursiers avec rôles super admin, owner, client et driver.",
    targetCustomers: ["sociétés de livraison", "coursiers locaux"],
    multiTenant: "needs-audit",
    saasEligible: true,
    demoUrls: [{ label: "Démo", url: "https://demo.smartwebinfotech.com" }],
    demoCredentials: [
      { role: "Super Admin", username: "superadmin@gmail.com", password: "123456", loginUrl: "https://demo.smartwebinfotech.com" },
      { role: "Owner", username: "owner@gmail.com", password: "123456", loginUrl: "https://demo.smartwebinfotech.com" },
      { role: "Customer", username: "customer@gmail.com", password: "123456", loginUrl: "https://demo.smartwebinfotech.com" },
      { role: "Driver", username: "driver@gmail.com", password: "123456", loginUrl: "https://demo.smartwebinfotech.com" },
    ],
    dependencies: [],
    externalCosts: [],
    riskFlags: ["Isolation multi-tenant à auditer"],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "smart-fleet-saas-vehicle-tracking",
    slug: "smart-fleet-saas-vehicle-tracking",
    categoryKey: "logistique",
    categoryLabel: "Logistique",
    selectionRank: 4,
    name: "Smart Fleet SaaS — Vehicle Tracking System",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/vehicle-management-saas-addon/50627270",
    regularPriceObservedUsd: 39,
    extendedPriceObservedUsd: 199,
    salesObserved: 60,
    observedAt: "2026-09-16",
    shortDescription: "Gestion de flottes et suivi de véhicules en SaaS : transporteurs, location, maintenance, drivers, fuel, dépenses.",
    targetCustomers: ["flottes", "transporteurs", "location de véhicules"],
    multiTenant: "needs-audit",
    saasEligible: true,
    demoUrls: [{ label: "Démo", url: "https://demo.smartwebinfotech.com" }],
    demoCredentials: [
      { role: "Super Admin", username: "superadmin@gmail.com", password: "123456", loginUrl: "https://demo.smartwebinfotech.com" },
      { role: "Owner", username: "owner@gmail.com", password: "123456", loginUrl: "https://demo.smartwebinfotech.com" },
      { role: "Manager", username: "manager@gmail.com", password: "123456", loginUrl: "https://demo.smartwebinfotech.com" },
    ],
    dependencies: [],
    externalCosts: [],
    riskFlags: ["Addon SaaS – isolation multi-tenant à auditer"],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "saas-gofleet-control",
    slug: "saas-gofleet-control",
    categoryKey: "logistique",
    categoryLabel: "Logistique",
    selectionRank: 5,
    name: "SaaS GoFleet Control",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/gofleet-complete-courier-delivery-management-system-with-web-app-admin-dashboard-driver-app/58388789",
    regularPriceObservedUsd: 304,
    salesObserved: 2,
    observedAt: "2026-09-16",
    shortDescription: "Système de gestion livraison courrier avec app web, dashboard admin et app driver. Prix élevé observé (304 $) pour très peu de ventes.",
    targetCustomers: ["sociétés de livraison", "coursiers"],
    multiTenant: "needs-audit",
    saasEligible: false,
    demoUrls: [
      { label: "Admin", url: "https://apptechmobile.com/apptech/Onfleet/index.php/Admin/login" },
      { label: "Dispatcher", url: "https://apptechmobile.com/apptech/Onfleet/Dispatch/login" },
      { label: "User (site)", url: "https://apptechmobile.com/apptech/Onfleet/Website/index" },
    ],
    demoCredentials: [
      { role: "Admin", username: "admin@gmail.com", password: "123456", loginUrl: "https://apptechmobile.com/apptech/Onfleet/index.php/Admin/login" },
      { role: "Dispatcher", username: "dispatch@gmail.com", password: "123456", loginUrl: "https://apptechmobile.com/apptech/Onfleet/Dispatch/login", note: "à revérifier" },
      { role: "User", username: "7225862195", password: "123456", loginUrl: "https://apptechmobile.com/apptech/Onfleet/Website/index" },
      { role: "Driver", username: "driver@gmail.com", password: "123456" },
    ],
    dependencies: [],
    externalCosts: [],
    riskFlags: ["Prix élevé (304 $) sans preuve de qualité – vrai multi-tenant non audité", "Dispatcher à revérifier", "Non éligible tant que le multi-tenant n'est pas audité"],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },

  /* ─────────────────────── WhatsApp & relation client ─────────────────────── */
  {
    id: "whatscrm",
    slug: "whatscrm",
    categoryKey: "whatsapp",
    categoryLabel: "WhatsApp & relation client",
    selectionRank: 1,
    name: "WhatsCRM",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/whatscrm-chatbot-flow-builder-api-access-whatsapp-crm-saas-system/51122205",
    regularPriceObservedUsd: 69,
    salesObserved: 1216,
    ratingObserved: 4.5,
    observedAt: "2026-09-16",
    shortDescription: "SaaS CRM WhatsApp avec chatbot, constructeur de flux, accès API, rôles admin/user/agent.",
    targetCustomers: ["services client", "équipes commerciales", "revendeurs SaaS WhatsApp"],
    multiTenant: "needs-audit",
    saasEligible: true,
    demoUrls: [{ label: "Démo", url: "https://crm.oneoftheprojects.com" }],
    demoCredentials: [
      { role: "Admin", username: "admin@admin.com", password: "Password@123", loginUrl: "https://crm.oneoftheprojects.com" },
      { role: "User", username: "user@user.com", password: "password", loginUrl: "https://crm.oneoftheprojects.com" },
      { role: "Agent", username: "john@agent.com", password: "password", loginUrl: "https://crm.oneoftheprojects.com" },
    ],
    dependencies: [],
    externalCosts: ["WhatsApp Cloud API / Meta (selon usage) — non inclus automatiquement dans MERCO"],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "wapi-whatsapp-crm-saas",
    slug: "wapi-whatsapp-crm-saas",
    categoryKey: "whatsapp",
    categoryLabel: "WhatsApp & relation client",
    selectionRank: 2,
    name: "Wapi — WhatsApp CRM SaaS",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/wapi-whatsapp-crm-saas-with-chatbot-flow-builder-api-automation-multitenant-system/62205973",
    regularPriceObservedUsd: 149,
    extendedPriceObservedUsd: 699,
    observedAt: "2026-09-16",
    shortDescription: "SaaS CRM WhatsApp multi-tenant : chatbot, constructeur de flux, automatisation et API.",
    targetCustomers: ["centres de contact", "équipes support", "revendeurs SaaS WhatsApp"],
    multiTenant: true,
    saasEligible: true,
    demoUrls: [
      { label: "Front", url: "https://wapi-front-red.vercel.app" },
      { label: "Admin", url: "https://wapi-admin.vercel.app" },
    ],
    demoCredentials: [
      { role: "Admin", username: "admin@example.com", password: "123456789", loginUrl: "https://wapi-admin.vercel.app" },
      { role: "User", username: "john@example.com", password: "123456789" },
      { role: "Agent", username: "jack@example.com", password: "123456789" },
    ],
    dependencies: [],
    externalCosts: ["WhatsApp / API externes possibles — non inclus automatiquement dans MERCO"],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "whoxa-business",
    slug: "whoxa-business",
    categoryKey: "whatsapp",
    categoryLabel: "WhatsApp & relation client",
    selectionRank: 3,
    name: "Whoxa Business",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/whoxa-business-crm-chat-messenger-nodejs-script-for-whatsapp-with-admin-panel/63265500",
    regularPriceObservedUsd: 79,
    observedAt: "2026-09-16",
    shortDescription: "CRM/chat messagerie WhatsApp en Node.js avec panneau admin. Il faut prévoir un VPS/root.",
    targetCustomers: ["équipes support", "centres de contact", "revendeurs SaaS WhatsApp"],
    techStack: ["Node.js", "PostgreSQL"],
    multiTenant: "needs-audit",
    saasEligible: true,
    demoUrls: [
      { label: "Super Admin", url: "https://whoxa-super-admin.vercel.app" },
      { label: "User / Agent (login)", url: "https://whoxacrmweb.vercel.app/login" },
    ],
    demoCredentials: [
      { role: "Super Admin", username: "admin@admin.com", password: "Admin@123", loginUrl: "https://whoxa-super-admin.vercel.app" },
      { role: "User", username: "alicejohn@yopmail.com", password: "123456", loginUrl: "https://whoxacrmweb.vercel.app/login" },
      { role: "Agent", username: "agent@yopmail.com", password: "123456", loginUrl: "https://whoxacrmweb.vercel.app/login" },
    ],
    dependencies: [],
    externalCosts: ["Hébergement VPS / accès root à prévoir selon l'usage"],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "wacrm-ai-messaging-saas",
    slug: "wacrm-ai-messaging-saas",
    categoryKey: "whatsapp",
    categoryLabel: "WhatsApp & relation client",
    selectionRank: 4,
    name: "WACRM — AI-Powered Messaging & Communication SaaS",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/swiftchat-the-ultimate-aipowered-messaging-communication-saas-platform/61419649",
    regularPriceObservedUsd: 79,
    observedAt: "2026-09-16",
    shortDescription: "SaaS de messagerie et communication propulsé par IA (Swiftchat/WACRM).",
    targetCustomers: ["équipes support", "centres de contact", "revendeurs SaaS WhatsApp"],
    multiTenant: "needs-audit",
    saasEligible: true,
    demoUrls: [{ label: "Démo", url: "https://wacrm.wrapcoders.com" }],
    demoCredentials: [
      { role: "User", username: "user@demo.com", password: "User123!", loginUrl: "https://wacrm.wrapcoders.com" },
      { role: "Agent", username: "agent@demo.com", password: "Agent123!", loginUrl: "https://wacrm.wrapcoders.com" },
      { role: "Admin", username: "admin@demo.com", password: "Admin123!", loginUrl: "https://wacrm.wrapcoders.com" },
    ],
    dependencies: [],
    externalCosts: ["IA / messaging externes possibles — non inclus automatiquement dans MERCO"],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
  {
    id: "wadesk-saas",
    slug: "wadesk-saas",
    categoryKey: "whatsapp",
    categoryLabel: "WhatsApp & relation client",
    selectionRank: 5,
    name: "WaDesk SaaS",
    sourcePlatform: "CodeCanyon / Envato Market",
    productUrl: "https://codecanyon.net/item/wadesk-saas-aipowered-whatsapp-crm-automation-chatbot-builder-and-bulk-messenger/63755235",
    regularPriceObservedUsd: 49,
    salesObserved: 144,
    ratingObserved: 4.86,
    observedAt: "2026-09-16",
    shortDescription: "SaaS WhatsApp IA : CRM, automatisation, chatbot builder et messagerie de masse.",
    targetCustomers: ["équipes support", "commerçants", "revendeurs SaaS WhatsApp"],
    multiTenant: "needs-audit",
    saasEligible: true,
    demoUrls: [{ label: "Démo", url: "https://wadesk.mediacity.co.in" }],
    demoCredentials: [
      { role: "Admin", username: "admin@mediacity.co.in", password: "12345678", loginUrl: "https://wadesk.mediacity.co.in" },
      { role: "Trial User", username: "trialuser@gmail.com", password: "12345678", loginUrl: "https://wadesk.mediacity.co.in" },
      { role: "Premium User", username: "user@mediacity.co.in", password: "12345678", loginUrl: "https://wadesk.mediacity.co.in" },
    ],
    dependencies: [],
    externalCosts: ["WhatsApp / IA externes possibles — non inclus automatiquement dans MERCO"],
    sourceVerified: true,
    licenseVerified: false,
    commerciallyAvailable: false,
    status: "research",
  },
];

/* ─────────────────────────── Helpers ─────────────────────────── */

export function getResearchSaaSBySlug(slug: string): ResearchSaaS | undefined {
  return researchCatalog.find((item) => item.slug === slug);
}

export function getResearchByCategory(categoryKey: string): ResearchSaaS[] {
  return researchCatalog.filter((item) => item.categoryKey === categoryKey);
}

export function getResearchCategoryLabel(categoryKey: string): string {
  return RESEARCH_CATEGORIES.find((c) => c.key === categoryKey)?.label ?? categoryKey;
}

/** Un candidat n'est commercialement disponible que si MERCO l'a validé manuellement. */
export function isResearchCommercialReady(item: ResearchSaaS): boolean {
  return (
    item.licenseVerified &&
    item.commerciallyAvailable &&
    item.saasEligible
  );
}

function waLink(message: string): string {
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`;
}

/** CTA demandé quand le produit n'est pas encore disponible (statut par défaut). */
export function researchVerificationMessage(productName: string): string {
  return `Bonjour MERCO 👋 Je suis intéressé par ${productName}. Pouvez-vous vérifier sa disponibilité, sa licence et sa compatibilité avec MERCO Business ?`;
}

export function researchVerificationLink(productName: string): string {
  return waLink(researchVerificationMessage(productName));
}

/** CTA affiché uniquement après validation manuelle MERCO (licenseVerified + commerciallyAvailable + active). */
export function researchSelectMessage(productName: string): string {
  return `Bonjour MERCO 👋 Je souhaite lancer le SaaS ${productName}. Pouvez-vous m'aider à l'ajouter à mon plan ?`;
}

export function researchSelectLink(productName: string): string {
  return waLink(researchSelectMessage(productName));
}